# http://travis-ci.org/#!/diyan/pywinrm
# pyenv used instead of native Python support in Travis CI to:
#  - Make build steps exactly the same on both Linux and Mac OS workers
#  - Make possible to debug build steps on local workstation
#  - Integrate new Python / PyPy releases earlier; pyenv does it with less lag than Travis
language: generic
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv
matrix:
  include:
    # Python 3.0-3.2 does not support explicit unicode literal, see pep-0414
    # Define 'sudo: false' to run on container-based workers
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=2.6.9 }
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=2.7.13 }
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=3.3.6 }
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=3.4.5 }
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=3.5.2 }
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=3.6-dev }
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=pypy2-5.6.0 }
    - { os: linux, dist: precise, sudo: false, env: UBUNTU=12.04 PYENV=pypy3.3-5.5-alpha }

    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=2.6.9 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=2.7.13 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.3.6 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.4.5 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.5.2 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.6-dev }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=pypy2-5.6.0 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=pypy3.3-5.5-alpha }

    - { os: osx, osx_image: xcode6.4, language: generic, env: OSX=10.10 PYENV=2.7.13 }
    - { os: osx, osx_image: xcode6.4, language: generic, env: OSX=10.10 PYENV=3.5.2 }

    - { os: osx, osx_image: xcode7, language: generic, env: OSX=10.11 PYENV=2.7.13 }
    - { os: osx, osx_image: xcode7, language: generic, env: OSX=10.11 PYENV=3.5.2 }

    - { os: osx, osx_image: xcode8.2, language: generic, env: OSX=10.12 PYENV=2.7.13 }
    - { os: osx, osx_image: xcode8.2, language: generic, env: OSX=10.12 PYENV=3.5.2 }

install:
  # Always use latest pyenv but keep installed Python versions in cache
  - git clone https://github.com/yyuu/pyenv.git ~/.pyenv || true
  - (cd ~/.pyenv && git pull)
  - export PATH="$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH"
  - pyenv --version
  - pyenv install --skip-existing $PYENV
  - pyenv global $PYENV
  - pyenv rehash
  - python --version
  - pip --version
  - pip install virtualenv
  - python -m virtualenv ~/.venv
  - source ~/.venv/bin/activate
  - pip install coveralls
  - pip install .[credssp]
  - pip install .[kerberos]
  - pip install -r requirements-test.txt
script:
  - py.test -v --pep8 --cov=winrm --cov-report=term-missing winrm/tests/

after_success:
  - coveralls
