environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\scripts\\run_with_compiler.cmd"
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "64"
init:
  # Override default Python version/architecture
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -c "import platform; print('Python', platform.python_version(), platform.architecture()[0])"
  - if not exist %PYTHON%\\Scripts\\pip.exe curl https://bootstrap.pypa.io/get-pip.py | python

install:
  - "%WITH_COMPILER% pip install coveralls"
  - winrm set winrm/config/service @{AllowUnencrypted="true"}
  - pip install -r requirements.txt

build: off  # Do not run MSBuild, build stuff at install step

build_script:
  - echo build_script

test_script:
  - WINRM_ENDPOINT='http://localhost' py.test -v --cov-report=term-missing --cov=.

after_test:
  - echo after_test